[package]
name = "bloco-de-notas"
version = "0.1.0"
edition = "2021"
description = "Um bloco de notas simples, rápido e escuro para Windows 10."
license = "MIT"
repository = "https://github.com/danilo-jesus-unifil/Bloco-de-notas"
readme = "README.md"
build = "build.rs"

[dependencies]
arboard = "3.4.1"
eframe = "0.29.1"
rfd = "0.14.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[profile.release]
opt-level = "z"
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"
